### GET request to example server
GET http://localhost:8080/post
Accept: application/json

###

### GET id
GET http://localhost:8080/post/6abe1019-b7c1-4464-bec8-7fc7cea6356f
Accept: application/json

###

### POST
POST http://localhost:8080/post
Content-Type: application/json

{
  "title": "React",
  "content": "We talk about the new version React 19. There are many things that change this lib.",
  "author": "JOHN DOE",
  "categoryName": "development"
}

###

### PUT`
PUT http://localhost:8080/post/6abe1019-b7c1-4464-bec8-7fc7cea6356f
Content-Type: application/json

{
  "title": "React 29",
  "content": "We talk about the new version React 19. There are many things that change this lib.",
  "author": "OTTO DE SOUZA",
  "categoryName": "development"
}

###

### DELETE
DELETE http://localhost:8080/post/9e01c9b1-7d86-4945-88d1-444502b4d23c
Content-Type: application/json


###