### GET request to example server
GET http://localhost:8080/post
Accept: application/json

###

### GET id
GET http://localhost:8080/post/b80c1214-62d7-4d50-a7ed-969cfefd6a02
Accept: application/json

###

### POST
POST http://localhost:8080/post
Content-Type: application/json

{
  "title": "",
  "content": "We talk about the new version React 19. There are many things that change this lib.",
  "author": "JOHN DOE",
  "category": "Development"
}

###

### PUT`
PUT http://localhost:8080/post/f4829497-d9de-433d-adb5-b9df55c31f23
Content-Type: application/json

{
  "title": "React 30",
  "content": "We talk about the new version React 19. There are many things that change this lib.",
  "author": "OTTO DE SOUZA",
  "category": "DEVELOPMENT"
}

###

### DELETE
DELETE http://localhost:8080/post/8cc1ee25-9c52-4f8a-9b1c-5802f6a46e03
Content-Type: application/json


###